# Generated by Django 5.0.1 on 2025-04-26 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimony',
            name='user',
        ),
    ]
