# Generated by Django 5.1.6 on 2025-11-13 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingevent',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube URL for past event recording (only used when event_status is "past")', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='upcomingevent',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='events/'),
        ),
    ]
