# Generated by Django 5.1.6 on 2025-11-13 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_upcomingevent_youtube_url_alter_upcomingevent_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcomingevent',
            name='image',
            field=models.ImageField(blank=True, help_text='Event poster/image (required for upcoming events)', max_length=500, null=True, upload_to='events/'),
        ),
    ]
