# Generated by Django 5.1.6 on 2025-04-30 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_churchproject_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimony',
            name='testimony_video',
            field=models.FileField(upload_to='uploads/testimony/'),
        ),
    ]
