# Generated by Django 5.1.6 on 2025-11-07 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_course_coursevideo_alter_churchproject_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchproject',
            name='image',
            field=models.ImageField(max_length=500, upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(max_length=500, upload_to='courses/'),
        ),
        migrations.AlterField(
            model_name='module',
            name='image',
            field=models.ImageField(max_length=500, upload_to='modules/'),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='testimony_video',
            field=models.ImageField(max_length=500, upload_to='testimonies/'),
        ),
        migrations.AlterField(
            model_name='upcomingevent',
            name='image',
            field=models.ImageField(max_length=500, upload_to='events/'),
        ),
        migrations.CreateModel(
            name='Devotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content_type', models.CharField(choices=[('text', 'Text'), ('video', 'Video')], max_length=10)),
                ('description', models.TextField()),
                ('text_content', models.TextField(blank=True, help_text='Devotional text content', null=True)),
                ('youtube_url', models.URLField(blank=True, help_text='YouTube video URL', null=True)),
                ('devotion_date', models.DateField(help_text='Date for this devotion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-devotion_date', '-created_at'],
                'unique_together': {('devotion_date',)},
            },
        ),
    ]
