# Generated by Django 5.1.6 on 2025-11-13 04:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_add_new_stream_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stream',
            options={'verbose_name_plural': 'Stream'},
        ),
        migrations.RemoveField(
            model_name='stream',
            name='is_live',
        ),
        migrations.AlterField(
            model_name='stream',
            name='stream_url',
            field=models.URLField(default='https://www.youtube.com/', help_text='URL of the live stream (YouTube, Facebook, etc.)', validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='stream',
            name='title',
            field=models.CharField(default='Live Stream', help_text='Title of the live stream', max_length=255),
        ),
    ]
