# Generated by Django 5.1.6 on 2025-04-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_testimony_testimony_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchproject',
            name='image',
            field=models.ImageField(upload_to='uploads/church_projects'),
        ),
        migrations.AlterField(
            model_name='upcomingevent',
            name='image',
            field=models.ImageField(upload_to='uploads/events'),
        ),
    ]
