# Generated by Django 5.1.6 on 2026-04-01 10:53

import api.models
import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_courseapplication'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(max_length=500, upload_to='projects/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(max_length=500, upload_to='courses/')),
                ('category', models.CharField(choices=[('sons_of_john_chi', 'Sons of John Chi'), ('mentorship', 'Mentorship')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('youtube_url', models.URLField()),
                ('key_takeaways', models.TextField(blank=True, null=True)),
                ('assignments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Devotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('text', 'Text'), ('video', 'Video')], max_length=10)),
                ('description', models.TextField()),
                ('text_content', models.TextField(blank=True, null=True, help_text='Devotional text content')),
                ('youtube_url', models.URLField(blank=True, null=True, help_text='YouTube video URL')),
                ('devotion_date', models.DateField(help_text='Date for this devotion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-devotion_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InspirationQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(max_length=500, upload_to='modules/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='api.course')),
            ],
        ),
        migrations.CreateModel(
            name='PrayerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField()),
                ('phone_number', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('request', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrayerRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Prayer Room', help_text='Title of the prayer room', max_length=200)),
                ('description', models.TextField(blank=True, null=True, help_text='Description of the prayer room')),
                ('is_active', models.BooleanField(default=False, help_text='Whether the prayer room is currently active')),
                ('youtube_url', models.URLField(blank=True, null=True, help_text='YouTube URL for the prayer stream (live or recorded)', validators=[django.core.validators.URLValidator()])),
                ('current_topic', models.CharField(default='General Prayer', help_text='Current prayer topic or focus', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Prayer Room',
                'verbose_name_plural': 'Prayer Room',
            },
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Live Stream', help_text='Title of the live stream', max_length=255)),
                ('description', models.TextField(blank=True, null=True, help_text='Optional description')),
                ('stream_url', models.URLField(default='https://www.youtube.com/', help_text='URL of the live stream (YouTube, Facebook, etc.)', validators=[django.core.validators.URLValidator()])),
                ('thumbnail_url', models.URLField(blank=True, null=True, help_text='Optional thumbnail image URL for the stream')),
                ('scheduled_time', models.DateTimeField(blank=True, null=True, help_text='Scheduled start time (optional)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Stream',
            },
        ),
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('testimony_text', models.TextField(blank=True, null=True)),
                ('testimony_video', models.FileField(help_text='Upload a video file (MP4, WebM, OGG)', max_length=500, upload_to='testimonies/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UpcomingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, help_text='Event poster/image (required for upcoming events)', max_length=500, upload_to='events/')),
                ('youtube_url', models.URLField(blank=True, null=True, help_text='YouTube URL for past event recording (only used when event_status is "past")', max_length=500)),
                ('event_date', models.DateTimeField()),
                ('event_status', models.CharField(choices=[('upcoming', 'Upcoming'), ('past', 'Past')], default='upcoming', max_length=10)),
                ('location', models.CharField(blank=True, null=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='api.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.coursevideo')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='coursevideo',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='api.module'),
        ),
        migrations.RemoveField(
            model_name='courseapplication',
            name='age',
        ),
        migrations.RemoveField(
            model_name='courseapplication',
            name='city',
        ),
        migrations.RemoveField(
            model_name='courseapplication',
            name='country',
        ),
        migrations.RemoveField(
            model_name='courseapplication',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='courseapplication',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='courseapplication',
            name='why_join',
        ),
        migrations.RenameField(
            model_name='courseapplication',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.AlterUniqueTogether(
            name='courseapplication',
            unique_together={('email', 'application_type')},
        ),
    ]
