# Generated by Django 5.1.6 on 2026-04-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_churchproject_course_coursevideo_devotion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_type', models.CharField(choices=[('video', 'General Video'), ('coursevideo', 'Course Video')], help_text='Type of video this translation belongs to', max_length=20)),
                ('video_id', models.PositiveIntegerField(help_text='ID of video this translation belongs to')),
                ('language', models.CharField(help_text='Language code of this translation (e.g., en, fr, es)', max_length=10)),
                ('language_display', models.CharField(help_text='Display name for the language (e.g., French, Spanish)', max_length=100)),
                ('translated_video_url', models.URLField(help_text='URL of the translated video')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Video Translation',
                'verbose_name_plural': 'Video Translations',
                'ordering': ['language_display'],
                'unique_together': {('video_type', 'video_id', 'language')},
            },
        ),
    ]
