# Generated by Django 5.1.6 on 2025-11-07 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_churchproject_image_alter_course_image_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='devotion',
            unique_together=set(),
        ),
    ]
