# Generated by Django 5.1.6 on 2026-04-02 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_add_video_translation'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE api_upcomingevent ADD COLUMN IF NOT EXISTS event_status VARCHAR(10) NOT NULL DEFAULT 'upcoming';",
            reverse_sql="ALTER TABLE api_upcomingevent DROP COLUMN IF EXISTS event_status;"
        ),
        migrations.RunSQL(
            "ALTER TABLE api_upcomingevent ADD COLUMN IF NOT EXISTS location VARCHAR(255) NULL;",
            reverse_sql="ALTER TABLE api_upcomingevent DROP COLUMN IF EXISTS location;"
        ),
    ]
