# Generated by Django 5.1.6 on 2025-11-07 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_devotion_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upcomingevent',
            options={'ordering': ['-event_date']},
        ),
        migrations.AddField(
            model_name='upcomingevent',
            name='event_status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('past', 'Past')], default='upcoming', max_length=10),
        ),
        migrations.AddField(
            model_name='upcomingevent',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
