# Generated by Django 5.1.6 on 2026-04-02 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_fix_event_status_field'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE api_upcomingevent ADD COLUMN IF NOT EXISTS location VARCHAR(255) NULL;",
            reverse_sql="ALTER TABLE api_upcomingevent DROP COLUMN IF EXISTS location;"
        ),
    ]
