# Generated by Django 5.1.6 on 2026-04-02 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_add_location_field'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE TABLE IF NOT EXISTS api_stream (
                id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                title varchar(255) NOT NULL DEFAULT 'Live Stream',
                description text NULL,
                stream_url varchar(200) NOT NULL DEFAULT 'https://www.youtube.com/',
                thumbnail_url varchar(200) NULL,
                scheduled_time timestamp with time zone NULL,
                created_at timestamp with time zone NOT NULL,
                updated_at timestamp with time zone NOT NULL
            );
            """,
            reverse_sql="DROP TABLE IF EXISTS api_stream;"
        ),
    ]
