# Generated by Django 5.1.6 on 2025-11-08 00:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_courseapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('stream_type', models.CharField(choices=[('youtube', 'YouTube Live'), ('video', 'Uploaded Video')], default='youtube', max_length=10)),
                ('youtube_url', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('video_file', models.FileField(blank=True, max_length=500, null=True, upload_to='streams/videos/')),
                ('is_active', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='courseapplication',
            unique_together={('email', 'application_type')},
        ),
    ]
