# Generated by Django 5.1.6 on 2025-11-08 00:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_stream_alter_courseapplication_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='video_file',
        ),
        migrations.AlterField(
            model_name='stream',
            name='stream_type',
            field=models.CharField(choices=[('live', 'YouTube Live'), ('regular', 'YouTube Video')], default='live', max_length=10),
        ),
        migrations.AlterField(
            model_name='stream',
            name='youtube_url',
            field=models.URLField(default=1, help_text='URL of the YouTube video or live stream', validators=[django.core.validators.URLValidator()]),
            preserve_default=False,
        ),
    ]
