# Generated by Django 5.1.6 on 2025-11-08 01:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_stream_video_file_alter_stream_stream_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the prayer room', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of the prayer room', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the prayer room is currently active')),
                ('current_topic', models.TextField(help_text='Current prayer topic or focus')),
                ('youtube_url', models.URLField(blank=True, help_text='YouTube URL for the prayer stream', null=True, validators=[django.core.validators.URLValidator()])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Prayer Room',
                'verbose_name_plural': 'Prayer Rooms',
                'ordering': ['-is_active', '-started_at'],
            },
        ),
    ]
