# Generated by Django 5.1.6 on 2025-11-08 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_prayerroom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prayerroom',
            options={'verbose_name': 'Prayer Room', 'verbose_name_plural': 'Prayer Room'},
        ),
        migrations.AlterField(
            model_name='prayerroom',
            name='current_topic',
            field=models.TextField(default='General Prayer', help_text='Current prayer topic or focus'),
        ),
        migrations.AlterField(
            model_name='prayerroom',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Whether the prayer room is currently active'),
        ),
        migrations.AlterField(
            model_name='prayerroom',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prayerroom',
            name='title',
            field=models.CharField(default='Prayer Room', help_text='Title of the prayer room', max_length=200),
        ),
    ]
