# Generated by Django 5.1.6 on 2025-11-08 01:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_prayerroom_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prayerroom',
            name='current_topic',
            field=models.CharField(default='General Prayer', help_text='Current prayer topic or focus', max_length=200),
        ),
        migrations.AlterField(
            model_name='prayerroom',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube URL for the prayer stream (live or recorded)', null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
