# Generated by Django 5.1.6 on 2025-11-08 02:49

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_prayerroom_current_topic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimony',
            name='testimony_video',
            field=models.FileField(help_text='Upload a video file (MP4, WebM, OGG)', max_length=500, upload_to=api.models.testimony_video_upload_path),
        ),
    ]
