# Generated by Django 5.1.6 on 2026-04-02 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_create_stream_table'),
        ('api', '0019_create_devotion_table'),
    ]

    operations = [
    ]
